spring.application.name=InfinitCart

spring.datasource.url=jdbc:mysql://localhost:3306/InfinitCart
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



jwt.secret=Rk4pQ8m8d1S7Jt3Xl9YQf6cM2VqWmZ8D4Rk4pQ8m8d1S7Jt3X
jwt.expiration=86400000
